FROM jboss/keycloak:15.0.2

ENV DB_ADDR test-keycloak-database:5432
ENV DB_DATABASE keycloak
ENV DB_PASSWORD keycloak
ENV DB_USER keycloak
ENV DB_VENDOR postgres

ENV KEYCLOAK_USER admin
ENV KEYCLOAK_PASSWORD admin
