quarkus:
  datasource:
    db-kind: postgresql
    password: test
    reactive:
      url: 'vertx-reactive:postgresql://test-database:5432/test'
    username: test
  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: 'import.sql'
  oidc:
    auth-server-url: 'http://test-keycloak:8080/auth/realms/bank'
    client-id: agency
    client-secret: '108f6914-0e39-4b8e-b983-56d5174301c7'
  package:
    type: uber-jar
